# Generated by Django 5.1.3 on 2024-11-22 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_film_options_alter_film_image'),
    ]

    operations = [
    ]
